// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zqdmclngcjsbtizaosji.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpxZG1jbG5nY2pzYnRpemFvc2ppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ0OTEzODksImV4cCI6MjA1MDA2NzM4OX0.FP7mz2oYqtcJ4CmuIcSm_mbyus7MOGCTso4yl8kPiPs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);